apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-test
  template:
    metadata:
      labels:
        app: deploy-test
    spec:
      containers:
      - name: example
        image: simple-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          hostPort: 3000
